### PR TITLE
knative-serving: Revert component's version to 1.8.0

### PR DESCRIPTION
**Pull request by orfeas-k**
Revert knative-serving version to 1.8.0 since knative-operator cannot fetch manifests for versions >=1.10.x. More details in #147

#### How to test the PR
1. Deploy `knative-operator`
2. Deploy `knative-serving` (from the PR's branch always)
3. Check that 
    - there is no error or sth weird in `knativeserving` CR conditions (`kubectl get knativeserving -n knative-serving -o yaml`)
    - it creates deployments that do not error out 
    - it spins up pods for each of the deployments in `knative-serving` namespace that go in `Running` state

### CODE REVIEW

**Comment by i-chvets** [comment]
Could not verify. Deployment failed.
```
juju deploy ./knative-operator_ubuntu-20.04-amd64.charm --trust --resource="knative-operator-image=gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.10.3" --resource="knative-operator-webhook-image=gcr.io/knative-releases/knative.dev/operator/cmd/webhook:v1.10.3"
juju deploy ./knative-serving_ubuntu-20.04-amd64.charm --trust
juju relate knative-operator knative-serving
```
Juju status:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  2.9.44   unsupported  11:30:54-04:00

App               Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
knative-operator           active       1  knative-operator             0  10.152.183.140  no       
knative-serving            waiting      1  knative-serving              0  10.152.183.73   no       installing agent

Unit                 Workload  Agent  Address     Ports  Message
knative-operator/0*  active    idle   10.1.59.74         
knative-serving/0*   error     idle   10.1.59.75         hook failed: "config-changed"

Relation provider                Requirer                        Interface       Type     Message
knative-operator:otel-collector  knative-serving:otel-collector  otel-collector  regular  
```
Error:
```
unit-knative-serving-0: 11:30:38 ERROR unit.knative-serving/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 190, in <module>
    main(KnativeServingCharm)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 107, in _on_config_changed
    self._apply_and_set_status()
  File "./src/charm.py", line 64, in _apply_and_set_status
    self.resource_handler.apply()
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py", line 340, in apply
    apply_many(
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/charmed_kubeflow_chisme/lightkube/batch/_many.py", line 72, in apply_many
    returns[i] = client.apply(
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/client.py", line 457, in apply
    return self.patch(type(obj), name, obj, namespace=namespace,
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/client.py", line 325, in patch
    return self._client.request("patch", res=res, name=name, namespace=namespace, obj=obj,
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 242, in request
    br = self.prepare_request(method, res, obj, name, namespace, watch, headers=headers, params=params)
  File "/var/lib/juju/agents/unit-knative-serving-0/charm/venv/lightkube/core/generic_client.py", line 173, in prepare_request
    raise ValueError("resource name not defined")
ValueError: resource name not defined
```

**Comment by i-chvets** [comment]
@orfeas-k Do we need to also change `metadata.yaml` to have versions 1.8.2 for workload containers?
https://github.com/canonical/knative-operators/blob/kf-4288-revert-knative-serving-to-1-8-2/charms/knative-operator/metadata.yaml#L22
https://github.com/canonical/knative-operators/blob/kf-4288-revert-knative-serving-to-1-8-2/charms/knative-operator/metadata.yaml#L25

**Comment by i-chvets** [comment]
Retried with 1.8.0 images - still same issue.
```
juju deploy ./knative-operator_ubuntu-20.04-amd64.charm --trust --resource="knative-operator-image=gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.8.0" --resource="knative-operator-webhook-image=gcr.io/knative-releases/knative.dev/operator/cmd/webhook:v1.8.0"
juju deploy ./knative-serving_ubuntu-20.04-amd64.charm --trust
juju deploy ./knative-serving_ubuntu-20.04-amd64.charm --trust
juju relate knative-operator knative-serving
```

**Review by i-chvets — APPROVED** [review]
Performed tests according to provided instructions. No errors in CR and all pods/deployments are up and running. No errors in the logs.
Logs for review test executions are added to this PR.

Approved.

**Review by NohaIhab — APPROVED** [review]
thanks @orfeas-k, verified by manual testing with istio latest/edge in non-kubeflow namespace.

**Pull request merged**
